schema: "classroom50/repo-config/v1"
classroom: "cse2506-fall2026"
assignment: "studio-ift"
owner:
  username: "izzymbatai"
  id: 161387177
  accepted_at: "2026-09-02T00:22:27Z"
source:
  owner: "ckelleher-wustl"
  owner_id: 75854859
  repo: "f22_IF_template"
  branch: "master"
